### ISSUE TITLE
license

### ISSUE THREAD

**Issue by fbagci** [thomasverelst/dynconv#9]
Thanks for your work.
What type of license this project has? MIT, GNU or anything else?

**Comment by thomasverelst** [comment]
MIT, so pretty open I guess :-)

**Comment by fbagci** [comment]
It is pretty open! It is not written anywhere but should I have guessed with my 6th sense

**Comment by thomasverelst** [comment]
No problem, it's not in the root but in the pose and classification subfolders, as I made them as seperate projects first, it's not super clear and I had to look for it myself.

**Comment by fbagci** [comment]
I just noticed the files now. Sorry for the confusion.
